<?php 

	$admin_login = true;
	
$arrTemplate=array(
					array(
						'domain'=>'dantri',
						'temp'=>'dantri-trangchu.html',
						'title'=>'Dantri-Trang chủ'
					),
					array(
						'domain'=>'dantri',
						'temp'=>'dantri-giaoduc.html',
						'title'=>'Dantri-giáo dục'
					),
					array(
						'domain'=>'dantri',
						'temp'=>'dantri-xahoi.html',
						'title'=>'Dantri-Xã hội'
					),
					array(
						'domain'=>'dantri',
						'temp'=>'dantri-vanhoa.html',
						'title'=>'Dantri-Văn hóa'
					),
					array(
						'domain'=>'dantri',
						'temp'=>'dantri-oto-xemay.html',
						'title'=>'Dantri- Ô tô xe máy'
					),
					array(
						'domain'=>'dantri',
						'temp'=>'dantri-nhipsongtre.html',
						'title'=>'Dantri- Nhịp sống trẻ'
					),
					array(
						'domain'=>'afamily',
						'temp'=>'afamily-trangchu.html',
						'title'=>'Afamily- Trang chủ'
					),
					array(
						'domain'=>'afamily',
						'temp'=>'afamily-doisong.html',
						'title'=>'Afamily - Đời sống'
					),
					array(
						'domain'=>'afamily',
						'temp'=>'afamily-mevabe.html',
						'title'=>'Afamily - Mẹ và bé'
					),
					array(
						'domain'=>'afamily',
						'temp'=>'afamily-tinhyeuhonnhan.html',
						'title'=>'Afamily - Tình yêu hôn nhân'
					),
					array(
						'domain'=>'afamily',
						'temp'=>'afamily-giaitri.html',
						'title'=>'Afamily - Giải trí'
					),
					array(
						'domain'=>'vneconomy',
						'temp'=>'vneconomy-taichinh.html',
						'title'=>'Vneconomy - Tài Chính'
					),
					array(
						'domain'=>'cafef',
						'temp'=>'cafef-trangchu.html',
						'title'=>'Cafef - Trang chủ'
					),
					
					array(
						'domain'=>'cafebiz',
						'temp'=>'cafebiz-trangchu.html',
						'title'=>'Cafebiz - Trang chủ'
					),
					
					array(
						'domain'=>'kenh14',
						'temp'=>'kenh14-trangchu.html',
						'title'=>'Kenh14 - Trang chủ'
					),
					array(
						'domain'=>'kenh14',
						'temp'=>'kenh14-hocduong.html',
						'title'=>'Kenh14 - Học đường'
					),
					array(
						'domain'=>'kenh14',
						'temp'=>'kenh14-xahoi.html',
						'title'=>'Kenh14 - Xã hội'
					),
					array(
						'domain'=>'kenh14',
						'temp'=>'kenh14-doisong.html',
						'title'=>'Kenh14 - Đời Sống'
					),
					array(
						'domain'=>'autopro',
						'temp'=>'autopro-trangchu.html',
						'title'=>'Autopro - Trang chủ'
					),
					array(
						'domain'=>'gamek',
						'temp'=>'gamek-console.html',
						'title'=>'Gamek - Pc-Console'
					),
					array(
						'domain'=>'genk',
						'temp'=>'genk-mobile.html',
						'title'=>'Genk - Mobile'
					),
					array(
						'domain'=>'giadinh',
						'temp'=>'giadinh-giadinh.html',
						'title'=>'Giadinh.net.vn - Gia-Dinh'
					),
					array(
						'domain'=>'soha',
						'temp'=>'soha-home.html',
						'title'=>'Soha.vn - Trang chủ'
					),
				);
$jsonTemplate=json_encode($arrTemplate);
$arrDefined=array(
	'dantri'=>array(
		221=>array(
			'size'=>'980x90',
			'width'=>980,
			'height'=>90,
			'sticky'=>false
		),
		401=>array(
			'size'=>'300x250',
			'width'=>300,
			'height'=>250,
			'sticky'=>false
		),
		345=>array(
			'size'=>'300x600',
			'width'=>300,
			'height'=>600,
			'sticky'=>true
		),
		1087=>array(
			'size'=>'300x600',
			'width'=>300,
			'height'=>600,
			'sticky'=>true
		),
		224=>array(
			'size'=>'300x250',
			'width'=>300,
			'height'=>250,
			'sticky'=>true
		),
		256=>array(
			'size'=>'300x250',
			'width'=>300,
			'height'=>250,
			'sticky'=>false
		),
		227=>array(
			'size'=>'300x600',
			'width'=>300,
			'height'=>600,
			'sticky'=>false
		),
		228=>array(
			'size'=>'160x600',
			'width'=>160,
			'height'=>600,
			'sticky'=>false
		),
		222=>array(
			'size'=>'336x600',
			'width'=>336,
			'height'=>600,
			'sticky'=>false
		)
		,230=>array(
			'size'=>'474x90',
			'width'=>474,
			'height'=>90,
			'sticky'=>false
		)
		
	),
	'afamily'=>array(
		437=>array(
			'size'=>'980x90',
			'width'=>980,
			'height'=>90,
			'sticky'=>false
		),
		438=>array(
			'size'=>'336x600',
			'width'=>336,
			'height'=>600,
			'sticky'=>false
		),
		436=>array(
			'size'=>'300x600',
			'width'=>300,
			'height'=>600,
			'sticky'=>false
		),
		150=>array(
			'size'=>'300x250',
			'width'=>300,
			'height'=>250,
			'sticky'=>false
		),
		342=>array(
			'size'=>'300x600',
			'width'=>300,
			'height'=>600,
			'sticky'=>true
		)
		
	),
	'cafef'=>array(
		96=>array(
			'size'=>'980x90',
			'width'=>980,
			'height'=>90,
			'sticky'=>false
		),
		97=>array(
			'size'=>'300x250',
			'width'=>300,
			'height'=>250,
			'sticky'=>false
		),
		172=>array(
			'size'=>'300x600',
			'width'=>300,
			'height'=>600,
			'sticky'=>false
		),
		344=>array(
			'size'=>'300x600',
			'width'=>300,
			'height'=>600,
			'sticky'=>true
		),
	),
	'cafebiz'=>array(
		4285=>array(
			'size'=>'980x90',
			'width'=>980,
			'height'=>90,
			'sticky'=>false
		),
		4288=>array(
			'size'=>'300x250',
			'width'=>300,
			'height'=>250,
			'sticky'=>false
		),
		4289=>array(
			'size'=>'300x600',
			'width'=>300,
			'height'=>600,
			'sticky'=>false
		),
		4290=>array(
			'size'=>'300x600',
			'width'=>300,
			'height'=>600,
			'sticky'=>true
		),
	),
	'autopro'=>array(
		77=>array(
			'size'=>'980x90',
			'width'=>980,
			'height'=>90,
			'sticky'=>false
		),
		78=>array(
			'size'=>'300x250',
			'width'=>300,
			'height'=>250,
			'sticky'=>false
		),
		79=>array(
			'size'=>'300x600',
			'width'=>300,
			'height'=>600,
			'sticky'=>false
		),
		343=>array(
			'size'=>'300x600',
			'width'=>300,
			'height'=>600,
			'sticky'=>true
		),
		
	),
	'vneconomy'=>array(
		195=>array(
			'size'=>'980x90',
			'width'=>980,
			'height'=>90,
			'sticky'=>false
		),
		196=>array(
			'size'=>'300x250',
			'width'=>300,
			'height'=>250,
			'sticky'=>false
		),
		197=>array(
			'size'=>'300x600',
			'width'=>300,
			'height'=>600,
			'sticky'=>false
		),
		351=>array(
			'size'=>'300x600',
			'width'=>300,
			'height'=>600,
			'sticky'=>true
		),
	),
	'kenh14'=>array(
		49=>array(
			'size'=>'980x90',
			'width'=>980,
			'height'=>90,
			'sticky'=>false
		),
		50=>array(
			'size'=>'300x250',
			'width'=>300,
			'height'=>250,
			'sticky'=>false
		),
		51=>array(
			'size'=>'300x250',
			'width'=>300,
			'height'=>250,
			'sticky'=>false
		),
		253=>array(
			'size'=>'300x600',
			'width'=>300,
			'height'=>600,
			'sticky'=>false
		),
		336=>array(
			'size'=>'300x600',
			'width'=>300,
			'height'=>600,
			'sticky'=>true
		),54=>array(
			'size'=>'980x90',
			'width'=>980,
			'height'=>90,
			'sticky'=>false
		),
	),'gamek'=>array(
		57=>array(
			'size'=>'980x90',
			'width'=>980,
			'height'=>90,
			'sticky'=>false
		),
		59=>array(
			'size'=>'300x250',
			'width'=>300,
			'height'=>250,
			'sticky'=>false
		),
		962=>array(
			'size'=>'300x600',
			'width'=>300,
			'height'=>600,
			'sticky'=>false
		),
		360=>array(
			'size'=>'300x600',
			'width'=>300,
			'height'=>600,
			'sticky'=>true
		),
	),
	'genk'=>array(
		57=>array(
			'size'=>'980x90',
			'width'=>980,
			'height'=>90,
			'sticky'=>false
		),
		59=>array(
			'size'=>'300x250',
			'width'=>300,
			'height'=>250,
			'sticky'=>false
		),
		962=>array(
			'size'=>'300x600',
			'width'=>300,
			'height'=>600,
			'sticky'=>false
		),
		360=>array(
			'size'=>'300x600',
			'width'=>300,
			'height'=>600,
			'sticky'=>true
		),
	),'soha'=>array(
		2238=>array(
			'size'=>'980x90',
			'width'=>980,
			'height'=>90,
			'sticky'=>false
		),
		2239=>array(
			'size'=>'300x250',
			'width'=>300,
			'height'=>250,
			'sticky'=>false
		),
		6953=>array(
			'size'=>'980x330',
			'width'=>980,
			'height'=>330,
			'sticky'=>false
		),
		2241=>array(
			'size'=>'300x600',
			'width'=>300,
			'height'=>600,
			'sticky'=>true
		),
	),
	'giadinh'=>array(
		130=>array(
			'size'=>'728x90',
			'width'=>728,
			'height'=>90,
			'sticky'=>false
		),
		131=>array(
			'size'=>'300x250',
			'width'=>300,
			'height'=>250,
			'sticky'=>false
		),
		133=>array(
			'size'=>'300x600',
			'width'=>300,
			'height'=>600,
			'sticky'=>false
		),
		347=>array(
			'size'=>'300x600',
			'width'=>300,
			'height'=>600,
			'sticky'=>true
		),
		134=>array(
			'size'=>'980x90',
			'width'=>980,
			'height'=>90,
			'sticky'=>false
		),
	),
);
$jsonDefined=json_encode($arrDefined);

?>